encuesta/urls.py
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('encuesta.views',
    url(r'^$', 'index', name="index"),
    url(r'^consultar/$', 'consultar', name="consultar"),
    url(r'^indicadores/$', 'indicadores', name="indicadores"),
    url(r'^ajax/organi/$', 'get_organi'),
    url(r'^ajax/munis/$', 'get_munis'),
    url(r'^ajax/comunies/$', 'get_comunies'),
    (r'^a/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^b/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^d/(?P<vista>[-\w]+)/$', '_get_view'),
    )

estudiocafe/urls.py
from django.conf.urls import patterns, include, url
from settings import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'estudiocafe.views.home', name='home'),
    # url(r'^estudiocafe/', include('estudiocafe.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^', include('encuesta.urls')),
    url(r'^', include('roya.urls')),
    url(r'^', include('produccion_cafe_finca.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

if DEBUG:
    urlpatterns += patterns('',
                (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
                )

roya/urls.py
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('roya.views',
    (r'^e/(?P<vista>[-\w]+)/$', '_get_view'),
     (r'^f/(?P<vista>[-\w]+)/$', '_get_view'),
  
    )

encuesta/models.py
# -*- coding: utf-8 -*-

from django.db import models
from lugar.models import Comunidad, Municipio, Departamento, Pais
from geoposition.fields import GeopositionField

# Create your models here.
class Entrevistado(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField()

    class Meta:
        verbose_name_plural = 'Entrevistados'

    def __unicode__(self):
        return self.nombre

class DuenoFinca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField()

    class Meta:
        verbose_name_plural = 'Dueños Fincas'

    def __unicode__(self):
        return self.nombre
    
class Organizacion(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Organizaciones'

    def __unicode__(self):
        return self.nombre

class Recolector(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Recolector'

    def __unicode__(self):
        return self.nombre

CHOICE_SEXO = (
        (1, 'Hombre'),
        (2, 'Mujer'),
        (3, 'Mancomunado'),
    )

#1.1
class Encuesta(models.Model):
    fecha = models.DateField('Fecha de recolección de datos')
    recolector = models.ForeignKey(Recolector)
    nombre = models.ForeignKey(Entrevistado, verbose_name=u'Nombre de entrevistado/a')
    cedula = models.CharField(max_length=50)
    dueno = models.ForeignKey(DuenoFinca, verbose_name='Dueño de la finca')
    sexo = models.IntegerField('Sexo del dueño de la finca', choices=CHOICE_SEXO)
    finca = models.CharField('Nombre de la finca', max_length=200, 
                                null=True, blank=True)
    pais = models.ForeignKey(Pais)
    departamento = models.ForeignKey(Departamento)
    municipio = models.ForeignKey(Municipio)
    comunidad = models.ForeignKey(Comunidad)
    position = position = GeopositionField(null=True, blank=True)
    altitud = models.IntegerField('altitud promedio',null=True, blank=True)
    beneficiarios = models.ManyToManyField(Organizacion, null=True, blank=True)


    class Meta:
        verbose_name_plural = '1.1 Información general '

    def __unicode__(self):
        return self.nombre.nombre
#1.2
class SocioOrganizacion(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Socios organizaciones"

    def __unicode__(self):
        return self.nombre

CHOICE_DESDE = (
            (1, 'Menos de 5 años'),
            (2, 'Más de 5 años'),
            (3, 'Ninguno'),
    )

class Beneficios(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Beneficio'
        verbose_name_plural = 'Beneficios'

    def __unicode__(self):
        return self.nombre

class CreditoE(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'credito'
        verbose_name_plural = 'creditos'

    def __unicode__(self):
        return self.nombre

class DeQuien(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Organizaciones que dan credito'
        verbose_name_plural = 'Organizaciones que dan creditos'

    def __unicode__(self):
        return self.nombre
    
class QuienFinancia(models.Model):
    socio = models.ManyToManyField(SocioOrganizacion, related_name="socios")
    desde = models.IntegerField(choices=CHOICE_DESDE, null=True, blank=True)
    beneficio_ser_socio = models.ManyToManyField(Beneficios, 
                                        related_name="beneficiario_socio",
                                        null=True, blank=True)
    tiene_credito = models.ManyToManyField(CreditoE, 
                                        related_name="credito",
                                        null=True, blank=True)
    de_quien = models.ManyToManyField(DeQuien, related_name="quien",
                                    null=True, blank=True)

    encuesta = models.ForeignKey(Encuesta)

    class Meta:
        verbose_name_plural = '1.2 Organización'

    def __unicode__(self):
        return 
    
#1.3
class ViveFamilia(models.Model):
    nombre = models.CharField(max_length=200)
    class Meta:
       
        verbose_name_plural = 'Vive Familias'

    def __unicode__(self):
        return self.nombre

CHOICE_EDUCACION = (
            (1, 'NSLE'),
            (2, 'PRIn'),
            (3, 'PRC'),
            (4, 'SECIN'),
            (5, 'Bach'),
            (6, 'Univ'),
    )

class Composicion(models.Model):
    adultos = models.IntegerField('adultos varones', null=True, blank=True)
    adultas = models.IntegerField('adultas mujeres', null=True, blank=True)
    jovenes_varones = models.IntegerField(null=True, blank=True)
    jovenes_mujeres = models.IntegerField(null=True, blank=True)
    ninos = models.IntegerField('niños', null=True, blank=True)
    ninas = models.IntegerField('niñas', null=True, blank=True)
    permanente_hombres = models.IntegerField(null=True, blank=True)
    permanente_mujeres = models.IntegerField(null=True, blank=True)
    temporales_hombres = models.IntegerField(null=True, blank=True)
    temporales_mujeres = models.IntegerField(null=True, blank=True)
    tecnico_hombres = models.IntegerField(null=True, blank=True)
    tecnico_mujeres = models.IntegerField(null=True, blank=True)
    relacion_finca_vivienda = models.ForeignKey(ViveFamilia,null=True, blank=True)
    educacion_dueno = models.IntegerField('Nivel de educación de dueño de la finca?', 
                                        choices=CHOICE_EDUCACION,null=True, blank=True)
    educacion_maxima_hombre = models.IntegerField('Nivel máximo de hombres de la finca?',
                                        choices=CHOICE_EDUCACION,null=True, blank=True)
    educacion_maxima_mujeres = models.IntegerField('Nivel máximo de las mujeres de la finca?',
                                        choices=CHOICE_EDUCACION,null=True, blank=True)

    encuesta = models.ForeignKey(Encuesta)

    class Meta:
       
        verbose_name_plural = '1.3 Composición del grupo familiar'

    def __unicode__(self):
        return self.encuesta.nombre.nombre

#1.4
class EnergiaFinca(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'EnergiaFinca'
        verbose_name_plural = 'EnergiaFincas'

    def __unicode__(self):
        return self.nombre

class Combustible(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Combustible en la cocina'
        verbose_name_plural = 'Combustibles en la cocina'

    def __unicode__(self):
        return self.nombre

class AguaFinca(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Disponibilidad de agua en la finca'
        verbose_name_plural = 'Disponibilidad de agua en la fincas'

    def __unicode__(self):
        return self.nombre
    
class ServiciosBasicos(models.Model):
    electricidad = models.ManyToManyField(EnergiaFinca, related_name="electricidad",
                                        null=True, blank=True)
    combustible = models.ManyToManyField(Combustible, related_name="combustible",
                                        null=True, blank=True)
    agua_trabajo_finca = models.ManyToManyField(AguaFinca, related_name="trabaja",
                                        null=True, blank=True)
    agua_consumo_humano = models.ManyToManyField(AguaFinca, related_name="consumo",
                                        null=True, blank=True)

    encuesta = models.ForeignKey(Encuesta)

    class Meta:
        verbose_name_plural = '1.4 Servicios básicos en la finca'

    def __unicode__(self):
        pass
    
#1.5
CHOICE_PARCELA = (
            (1, 'Propia con escritura pública'),
            (2, 'Propias con Promesa de venta'),
            (3, 'Arrendada'),
            (4, 'Propia por herencia'),
            (5, 'Propias con título de reforma agraria'),
            (6, 'Parcela en tierra comunitaria'),
            (7, 'Sin documento'),
    )
CHOICE_DOCUMENTO = (
            (1, 'Hombre'),
            (2, 'Mujer'),
            (3, 'Mancomunado'),
            (4, 'Parientes'),
            (5, 'Colectivo'),
            (6, 'No hay'),
    )

class Tenecia(models.Model):
    tipo = models.IntegerField('Tipo de tenencia de parcela', choices=CHOICE_PARCELA)
    documento = models.IntegerField('Documento legal de la parcela, a nombre de quién', 
                                                            choices=CHOICE_DOCUMENTO)

    encuesta = models.ForeignKey(Encuesta)
    
    class Meta:
        verbose_name_plural = '1.5 Tenencia de la tierras'

    def __unicode__(self):
        pass
    

#1.6
CHOICE_ALIMENTOS_COMPRA = (
            (1, 'Todo'),
            (2, 'Más de la Mitad'),
            (3, 'Menos de la Mitad'),
            (4, 'Nada '),
           
    )

CHOICE_SI_NO = (
            (1, 'Si'),
            (2, 'No'),
           
    )

class NecesidadAlimento(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Necesidad Alimentos'

    def __unicode__(self):
        return self.nombre
    
class Meses(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Meses del año'

    def __unicode__(self):
        return self.nombre

class TiemposCrisis(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Tiempo de crisis'

    def __unicode__(self):
        return self.nombre
    
class Seguridad(models.Model):
    compra_alimento = models.IntegerField('¿Qué parte de alimentos básicos que consume la familia o la en la finca se compra?',
                                                                            choices=CHOICE_ALIMENTOS_COMPRA,null=True, blank=True)

encuesta/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from encuesta.models import *
from lugar.models import *
from produccion_cafe_finca.models import *

def get_anios():
    years = []
    for en in Encuesta.objects.order_by('fecha__year').values_list('fecha__year', flat=True):
        years.append((en, en))
    return list(set(years))

CHOICE_EDUCACION = (
            ('', '------'),
            (1, 'NSLE'),
            (2, 'PRIn'),
            (3, 'PRC'),
            (4, 'SECIN'),
            (5, 'Bach'),
            (6, 'Univ'),
    )
def departamentos():   
    return Encuesta.objects.all().order_by('municipio__departamento__nombre').distinct().values_list('municipio__departamento__id', 'municipio__departamento__nombre')

CHOICE_ALTITUD = (
            ('', '-----'),
            (1, '400-800'),
            (2, '801-1200'),
            (3, 'Más de 1201'),
    )

CHOICE_AREA_FINCA = (
            ('', '------'),
            (1, '1-10 mz'),
            (2, '11-50 mz'),
            (3, 'Más de 50'),
    )

CHOICE_AREA_CAFE = (
             ('', '------'),
            (1, '1-10 mz'),
            (2, '11-50 mz'),
            (3, 'Más de 50'),
    )

CHOICE_REDUCCION = (
             ('', '------'),
            (1, '0% - 10%'),
            (2, '11% - 30%'),
            (3, 'Más de 31%'),
    )


class ConsultarForm(forms.Form):
    #anio = forms.ChoiceField(choices=get_anios(), label=u'Año')
    departamento = forms.MultipleChoiceField(choices=departamentos(), required=False, label=u'Departamentos')
    municipio = forms.ModelMultipleChoiceField(queryset=Municipio.objects.all().order_by('nombre'), required=False)
    #comunidad = forms.ModelMultipleChoiceField(queryset=Comunidad.objects.all(), required=False)
    altitud = forms.ChoiceField(choices=CHOICE_ALTITUD,required=False)
    empresa = forms.ModelMultipleChoiceField(queryset=Organizacion.objects.all().order_by('nombre'), 
                                                                                required=False, label=u'Empresa')
    area_finca = forms.ChoiceField(choices=CHOICE_AREA_FINCA, required=False)
    area_cafe = forms.ChoiceField(choices=CHOICE_AREA_CAFE, required=False)
    nivel_educacion = forms.ChoiceField(choices=CHOICE_EDUCACION, required=False)
    variedad_predominate = forms.ModelMultipleChoiceField(queryset=VariedadPredominante.objects.order_by('nombre'), 
                                                required=False)
    variedad_viviero = forms.ModelMultipleChoiceField(queryset=Variedades.objects.order_by('nombre'),
                                                required=False)
    reduccion_cosecha = forms.ChoiceField(choices=CHOICE_REDUCCION,required=False)
    credito = forms.ModelChoiceField(queryset=CreditoE.objects.all(),required=False)

templates/encuesta/actitud.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         Actitud<a href="/indicadores"></a>   
        </div>
        <li><a href="/c/beneficiados/">Beneficiado 1</a></li>
        <li><a href="/c/beneficiado/">Beneficiado 2</a></li>
        <li><a href="/d/precio/">La comercialización</a></li>
        <li><a href="/d/credito/">Crédito para la producción de café</a></li>
    </ul>
</div>
{% endblock %}

templates/encuesta/conocimiento.html
{% block content %}
<div class="menu_indicadores">
<ul>
        <div class="titulo_menu">
         Salidas<a href="/indicadores"></a>   
        </div>
        <li><a href="/c/beneficiados/">Beneficiado 1</a></li>
        <li><a href="/c/beneficiado/">Beneficiado 2</a></li>
        <li><a href="/d/precio/">La comercialización</a></li>
        <li><a href="/d/credito/">Crédito para la producción de café</a></li>
        
    </ul>
</div>
{% endblock %}

templates/encuesta/consultar.html
{% extends "base.html" %}
{% block extratitle %}Consultar{% endblock %}

{% block extrahead %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<script src="/static/js/cufon-yui.js" type="text/javascript"></script>
<script src="/static/js/libel.font.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function($) {
        Cufon.replace('.titulo');
    });
</script>
<script src="/static/js/jquery.multiselect.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.multiselect.filter.js" type="text/javascript"></script>
<link href="/static/css/jquery.multiselect.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
    var organizacion;
    var comunidad;
    var municipio;
    $(document).ready(function(){
        $("#id_municipio, #id_comunidad").html('');
        comunidad = $("#id_comunidad").multiselect({
            noneSelectedText: 'Seleccione elementos',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200
        });
           organizacion = $("#id_empresa").multiselect({
            noneSelectedText: 'Seleccione la organizacion',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200,
         
        });

           variedad = $("#id_variedad_predominate").multiselect({
            noneSelectedText: 'Seleccione las variedades',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200,
         
        });

           viviero = $("#id_variedad_viviero").multiselect({
            noneSelectedText: 'Seleccione vivieros',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200,
         
        });

        $("#id_departamento").multiselect({
            noneSelectedText: 'Seleccione elementos',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200,
            beforeclose: function(event, ui){
                var selectos = $("#id_departamento").multiselect("getChecked").map(function(){
                    return this.value;
                }).get();
                if(selectos.length!=0){
                    filtrarMunicipio(selectos, 1);
                    //filtrarOrganizacion(selectos);
                }else{
                    //organizacion.multiselect("disable");
                    municipio.multiselect("disable");
                }
            }
        });

        municipio = $("#id_municipio").multiselect({
            noneSelectedText: 'Seleccione elementos',
            selectedText: '# seleccionados',
            checkAllText: 'Todos',
            uncheckAllText: 'Quitar seleccion',
            minWidth: 200,
            beforeclose: function(event, ui){
                var selectos = $("#id_municipio").multiselect("getChecked").map(function(){
                    return this.value;
                }).get();
                if(selectos.length!=0){
                    $.getJSON('/ajax/comunies/?ids='+selectos.join(","), function(data){
                        $('#id_comunidad').html('');
                        if(data){
                            $.each(data, function(i, item){
                                comunidad.append($('<option></option>').val(item.id).html(item.nombre));
                                comunidad.multiselect('refresh');
                            });
                        }
                    });
                    comunidad.multiselect("enable");
                }
                else{
                    comunidad.multiselect("disable");
                }
            }
        });
        municipio.multiselect("disable");
        //organizacion.multiselect("disable");
        comunidad.multiselect("disable");
    });
    function filtrarMunicipio(selectos, opcion){
        if (opcion == 1){
            var url = '/ajax/munis/?ids='+selectos.join(",");
        }else{
            var url = '/ajax/munis/?org_ids='+selectos.join(",");
        }
        $.getJSON(url, function(data){
            $('#id_municipio').html('');
            if(data){
                $.each(data, function(i, item){
                    $.each(item, function(j, item2){
                        var group = $('<optgroup></optgroup>').attr('label', j);
                        $.each(item2, function(k, item3){
                            group.append($('<option></option>').val(item3.id).html(item3.nombre));
                        });
                        group.appendTo(municipio);
                    });
                    municipio.multiselect('refresh');
                    municipio.multiselect('enable');
                });
            }
        });
    }

    function filtrarOrganizacion(selectos){
        $.getJSON('/ajax/organi/?ids='+selectos.join(","), function(data){
            $("#id_empresa").html('');
            if(data){
                $.each(data, function(i, item){
                    $('<option></option>').val(item.id).html(item.nombre_corto).appendTo(organizacion)
                });
                organizacion.multiselect('refresh');
                organizacion.multiselect("enable");
            }
        });
    }
</script>
<style type="text/css">
    .nav .consultas a{
        background-position: -44px -14px;
    }
</style>
{% endblock %}

{% block content %}
<div>
    <form method="POST" action="." id="consultar-form">{% csrf_token %}
        <div class="general">
            <div class="titulo">Filtro1 <a href="/generales"><img  style ="margin-right:5px;margin-top:-5px;"align='right' src="/static/img/generales1.jpg"></a></div>
            <div class="label">{{form.departamento.label}}</div>
            <div class="filtros">{{form.departamento}}<br>{{form.departamento.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.municipio.label}}</div>
            <div class="filtros">{{form.municipio}}<br>{{form.municipio.errors}}</div>
            <div class="clean"></div>
             <div class="label">{{form.altitud.label}}</div>
            <div class="filtros">{{form.altitud}}<br>{{form.altitud.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.empresa.label}}</div>
            <div class="filtros">{{form.empresa}}<br>{{form.empresa.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.area_finca.label}}</div>
            <div class="filtros">{{form.area_finca}}<br>{{form.area_finca.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.area_cafe.label}}</div>
            <div class="filtros">{{form.area_cafe}}<br>{{form.area_cafe.errors}}</div>
            <div class="clean"></div>
            
        </div>
        <div class="lugar">
            <div class="titulo">Datos Filtro2</div>
            <div class="label">{{form.nivel_educacion.label}}</div>
            <div class="filtros">{{form.nivel_educacion}}<br>{{form.nivel_educacion.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.variedad_predominate.label}}</div>
            <div class="filtros">{{form.variedad_predominate}}<br>{{form.variedad_predominate.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.variedad_viviero.label}}</div>
            <div class="filtros">{{form.variedad_viviero}}<br>{{form.variedad_viviero.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.reduccion_cosecha.label}}</div>
            <div class="filtros">{{form.reduccion_cosecha}}<br>{{form.reduccion_cosecha.errors}}</div>
            <div class="clean"></div>
            <div class="label">{{form.credito.label}}</div>
            <div class="filtros">{{form.credito}}<br>{{form.credito.errors}}</div>
            <div class="clean"></div>
           
        </div>
            {% if nono %}
        <div class="clean"></div>
        <div id="mensaje">
             No hay datos para estas selecciones, vuelva a crear otra consulta por favor
        </div>
    {% endif %}
        <button class="consultar">EXPLORAR RESULTADOS</button>
    </form>

</div>
<div class="clean"></div>
{% endblock %}

templates/encuesta/estado.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         Salidas<a href="/indicadores"></a>   
        </div>
            <li><a href="/e/incidencia-enfermedades/" >Incidendia enfermedades</a></li>
            <li><a href="/e/impacto-roya/" >Impacto de la roya</a></li>
            <li><a href="/e/cambio-poda/" >Cambio de poda</a></li>
            <li><a href="/e/cambio-recepo/" >Cambio de recepo</a></li>
            <li><a href="/e/cambio-variedad/" >Cambio de variedades</a></li>
            <li><a href="/e/manejo-sombra/" >Cambio de manejo de sombra</a></li>
            <li><a href="/e/fertilizacion/" >Cambio de fertilización</a></li>
            <li><a href="/e/fungicidas/" >Cambio de fungicidas</a></li>
    </ul>
</div>
{% endblock %}

templates/encuesta/familia.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         información general<a href="/indicadores"></a>   
        </div>
            <li><a href="/a/informacion/">Informacion General</a></li>
            <li><a href="/a/ubicacion/">Ubicacion</a></li>
            <li><a href="/a/servicios/">Servicios basicos</a></li>
            <li><a href="/a/dependientes/">Dependientes</a></li>
            <li><a href="/a/conexion/">Conexiones</a></li>
            <li><a href="/a/recursos/">Los recursos naturales</a></li>
    </ul>
</div>
{% endblock %}

templates/encuesta/percepcion.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         Percepción<a href="/indicadores"></a>   
        </div>
       <li><a href="/f/asistencia/" >Asistencia técnica</a></li>
        <li><a href="/f/futuro/">Perspectivas para el futuro</a></li>
    </ul>
</div>
{% endblock %}

templates/encuesta/practica.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         Salidas<a href="/indicadores"></a>   
        </div>
        <li><a href="/b/produccion/">Producción de café</a></li>
        <li><a href="/b/incidencia/">Variedad, incidencia roya</a></li>
        <li><a href="/b/vivero/">Vivero</a></li>
        <li><a href="/b/autoevaluacion/">Auto evaluacion manejo de cafetales</a></li>
        <li><a href="/b/momentos/">Momentos de manejo</a></li>
        <li><a href="/b/insumos/">Uso de insumos</a></li>
        <li><a href="/b/agroecologicos/">Uso de opciones agroecologicas</a></li>
    </ul>
</div>
{% endblock %}

templates/encuesta/seguridades.html
{% block content %}
<div class="menu_indicadores">
    <ul>
        <div class="titulo_menu">
         Salidas<a href="/indicadores"></a>   
        </div>
            <li><a href="/g/seguridad/" >Seguridad y riesgos</a></li>
            <li><a href="/g/elclima/">El clima</a></li>
            <li><a href="/g/elsuelo/">El suelo</a></li>
            <li><a href="/g/otros/">Otros riesgos</a></li>
            <li><a href="/g/mitigar/">Mitigación de los riesgos</a></li>  
    </ul>
</div>
{% endblock %}